"""Download the FULL LIDC-IDRI collection (real CT DICOM series) via the TCIA/NBIA REST API.

Unlike download_lidc.py (which only grabs small XML annotation files), this script
downloads the actual real CT scan volumes for every patient in the LIDC-IDRI collection.
No synthetic data is generated by this script -- everything comes from TCIA.

This is a large, multi-hour download (~1010 patients, ~100-400MB each, 100+ GB total).
The script is resumable: patients already downloaded (complete marker present) are skipped.

Usage:
    python scripts/download_lidc_full.py --output_dir data/raw/lidc
    python scripts/download_lidc_full.py --output_dir data/raw/lidc --limit 50   # partial run
    python scripts/download_lidc_full.py --output_dir data/raw/lidc --resume     # continue
"""

import sys
import os
import io
import json
import time
import zipfile
import argparse
from pathlib import Path

sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))

import requests

requests.packages.urllib3.disable_warnings()

NBIA_API = "https://services.cancerimagingarchive.net/nbia-api/services/v1"
COLLECTION = "LIDC-IDRI"
MIN_CT_IMAGES = 40

ANNOTATIONS_URL = "https://www.cancerimagingarchive.net/wp-content/uploads/LIDC-XML-only.zip"


def get_all_patient_ids() -> list:
    r = requests.get(f"{NBIA_API}/getPatient", params={"Collection": COLLECTION},
                      timeout=30, verify=False)
    r.raise_for_status()
    return sorted(p["PatientId"] for p in r.json())


def get_best_ct_series(patient_id: str) -> dict:
    """Return the series dict for the largest CT (volumetric) series for a patient."""
    r = requests.get(f"{NBIA_API}/getSeries", params={
        "Collection": COLLECTION, "PatientID": patient_id,
    }, timeout=30, verify=False)
    r.raise_for_status()
    series_list = r.json()

    ct_series = [s for s in series_list if s.get("Modality") == "CT"
                 and s.get("ImageCount", 0) >= MIN_CT_IMAGES]
    if not ct_series:
        return None
    return max(ct_series, key=lambda s: s.get("ImageCount", 0))


def download_series(series_uid: str, dest_dir: Path, retries: int = 4) -> int:
    """Download and extract a DICOM series ZIP. Returns number of DICOM files written."""
    dest_dir.mkdir(parents=True, exist_ok=True)
    last_err = None
    for attempt in range(retries):
        try:
            r = requests.get(f"{NBIA_API}/getImage", params={"SeriesInstanceUID": series_uid},
                              timeout=180, verify=False, stream=True)
            r.raise_for_status()
            buf = io.BytesIO(r.content)
            with zipfile.ZipFile(buf) as z:
                z.extractall(dest_dir)
            return len(list(dest_dir.glob("*.dcm")))
        except Exception as e:
            last_err = e
            time.sleep(2 ** attempt)
    raise RuntimeError(f"Failed to download series {series_uid}: {last_err}")


def download_annotations(output_dir: Path):
    """Download LIDC nodule malignancy XML annotations (small, ~8MB)."""
    xml_dir = output_dir / "annotations"
    if xml_dir.exists() and any(xml_dir.rglob("*.xml")):
        print("Annotations already downloaded.")
        return
    print("Downloading LIDC nodule annotation XML files...")
    r = requests.get(ANNOTATIONS_URL, timeout=120, verify=False)
    r.raise_for_status()
    xml_dir.mkdir(parents=True, exist_ok=True)
    with zipfile.ZipFile(io.BytesIO(r.content)) as z:
        z.extractall(xml_dir)
    n = len(list(xml_dir.rglob("*.xml")))
    print(f"  Extracted {n} XML annotation files")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--output_dir", default="data/raw/lidc")
    ap.add_argument("--limit", type=int, default=None, help="Only process first N patients")
    ap.add_argument("--start_index", type=int, default=0)
    args = ap.parse_args()

    output_dir = Path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    log_path = output_dir / "download_progress.json"

    progress = {}
    if log_path.exists():
        progress = json.loads(log_path.read_text())

    download_annotations(output_dir)

    print("Fetching full LIDC-IDRI patient list from TCIA...")
    patient_ids = get_all_patient_ids()
    print(f"Total patients in LIDC-IDRI: {len(patient_ids)}")

    if args.limit:
        patient_ids = patient_ids[args.start_index: args.start_index + args.limit]
    else:
        patient_ids = patient_ids[args.start_index:]

    n_done = sum(1 for v in progress.values() if v.get("status") == "ok")
    print(f"Already completed: {n_done}")

    t0 = time.time()
    for i, pid in enumerate(patient_ids):
        if progress.get(pid, {}).get("status") == "ok":
            continue

        patient_dir = output_dir / pid
        try:
            series = get_best_ct_series(pid)
            if series is None:
                progress[pid] = {"status": "no_ct_series"}
                print(f"[{i+1}/{len(patient_ids)}] {pid}: no CT series found, skipping")
                continue

            n_files = download_series(series["SeriesInstanceUID"], patient_dir)
            progress[pid] = {
                "status": "ok",
                "series_uid": series["SeriesInstanceUID"],
                "n_files": n_files,
                "image_count": series.get("ImageCount"),
            }
            elapsed = time.time() - t0
            done_now = sum(1 for v in progress.values() if v.get("status") == "ok")
            print(f"[{i+1}/{len(patient_ids)}] {pid}: OK ({n_files} DICOM files) "
                  f"| total_ok={done_now} | elapsed={elapsed/60:.1f}min")

        except Exception as e:
            progress[pid] = {"status": "error", "error": str(e)}
            print(f"[{i+1}/{len(patient_ids)}] {pid}: FAILED ({e})")

        log_path.write_text(json.dumps(progress, indent=2))

    n_ok = sum(1 for v in progress.values() if v.get("status") == "ok")
    n_err = sum(1 for v in progress.values() if v.get("status") == "error")
    n_none = sum(1 for v in progress.values() if v.get("status") == "no_ct_series")
    print("\n" + "=" * 60)
    print("LIDC-IDRI DOWNLOAD SUMMARY")
    print("=" * 60)
    print(f"  Downloaded OK : {n_ok}")
    print(f"  No CT series  : {n_none}")
    print(f"  Errors        : {n_err}")
    print(f"  Output dir    : {output_dir}")


if __name__ == "__main__":
    main()